services:

  main:
    build:
      context: .
      target: main  # Из Dockerfile
    restart: unless-stopped
    ports:
      - "${INTERFACE}:${EXTERNAL_APP_PORT}:${INTERNAL_APP_PORT}"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env
    volumes:
      - downloads:/downloads
    networks:
        - local

  anidb:
    build:
      context: .
      target: anidb
    restart: unless-stopped
    ports:
      - "${INTERFACE}:8081:8081"  # Внешний:внутренний
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env
    volumes:
      - downloads:/downloads
    networks:
      - local

  anilist:
    build:
      context: .
      target: anilist
    restart: unless-stopped
    ports:
      - "${INTERFACE}:8082:8082"  # Внешний:внутренний
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env
    volumes:
      - downloads:/downloads
    networks:
      - local

  animetosho:
    build:
      context: .
      target: animetosho
    restart: unless-stopped
    ports:
      - "${INTERFACE}:8083:8083"  # Внешний:внутренний
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env
    volumes:
      - downloads:/downloads
    networks:
      - local

  shikimori:
    build:
      context: .
      target: shikimori
    restart: unless-stopped
    ports:
      - "${INTERFACE}:8084:8084"  # Внешний:внутренний
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file:
      - .env
    volumes:
      - downloads:/downloads
    networks:
      - local
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${INTERFACE}:${DB_PORT}:${DB_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U matrix -d anime_db"]
      interval: 3s
      timeout: 5s
      retries: 5
    networks:
        - local

  pgadmin:
    image: dpage/pgadmin4:9
    restart: unless-stopped
    ports:
      - "5050:80" # pgAdmin на 5050 порту хоста
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'               # отключаем master password
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin   # чтобы настройки сохранялись
    networks:
    - local

volumes:
  pgdata:
  pgadmin-data:
  downloads:  # Новый volume для файлов (локально: ./downloads)

networks:
    local:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${SUBNET}
                  gateway: ${INTERFACE}